blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view()),
    path('create/', ArticleCreateView.as_view()),
    path('<int:pk>/', ArticleDetailView.as_view()),
    # path('<int:id>/', update_poll, name='update_poll'),
]

charliwallet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="home"),
    path('', include('charliauth.urls')),
    path('dashboard/', TemplateView.as_view(template_name="dashboard/index.html"), name="dashboard"),
    path('poll/', include('poll.urls')),
    path('employee/', include('employee.urls')),
    path('blogs/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *

app_name = 'poll'
urlpatterns = [
    path('', index, name='polls_home'),
    path('add/', poll_add, name='poll_add'),
    path('<int:id>/details/', details, name='poll_details'),
    path('<int:id>/', update_poll, name='update_poll'),
]

charliwallet/templates/partials/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-danger fixed-top">
    <a class="navbar-brand" href="{% url 'home' %}">CHARLIWALLET</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employee_list' %}">Employee</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'poll:polls_home' %}">Polls <span class="badge badge-primary badge-pill">{{ count_polls }}</span></a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown link
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
    </div>
</nav>